[theme]
# Primary accent color for interactive elements.
primaryColor = "#00E7FE"

# Background color for the main content area.
backgroundColor = "#000D2C"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#23929E"

# Color used for almost all text.
textColor = "#fafafa"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"

